name: Alert Sync Issues

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:


permissions:
  contents: read
jobs:
  alert-sync:
    uses: KooshaPari/phenoShared/.github/workflows/reusable/ci.yml@5e6c1f05d696d056b24df431401b4632b01be0d3
    with:
      auto-label: auto-alert-sync
